[package]
name = "xxx_chat_service"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.26.2"
tungstenite = "0.26.2"
futures-util = "0.3.31"